### ISSUE TITLE
Export as doesn't function with latest nightly on windows 

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#56] opened 2020-07-08 18:04 UTC
this is with 4.11.0-2020-07-07 r29207 / dad86b0

* also Export As still appears only in the Markups. 

```


Loading Slicer RC file [C:/Users/murat/.slicerrc.py]
Volume nodes will be stored uncompressed by default
Segmentation nodes will be stored uncompressed
parent qSlicerScriptedFileWriter (QObject 0x00000212AAA2A870)
Write {'fileName': 'C:/Users/murat/Desktop/C.fcsv', 'nodeID': 'vtkMRMLMarkupsCurveNode1'}
Traceback (most recent call last):
  File "C:/Users/murat/AppData/Roaming/NA-MIC/Extensions-29207/SlicerMorph/lib/Slicer-4.11/qt-scripted-modules/MarkupsFcsv.py", line 58, in write
    self.parent.writtenNodes = [markupNode.GetID()]
AttributeError: 'writtenNodes' does not exist on qSlicerScriptedFileWriter and creating new attributes on C++ objects is not allowed
Could not save C to C:/Users/murat/Desktop/C.fcsv


```
![image](https://user-images.githubusercontent.com/21285140/86954185-64036800-c10a-11ea-8a5a-bf1c1b1fa217.png)

**Comment by pieper** [comment] 2020-07-08 20:15
Yes, that is this issue waiting to be merged: https://github.com/Slicer/Slicer/pull/5025

**Comment by SlicerMorph** [comment] 2020-07-19 07:18
Slicer issue merged, functioning as intended

**Closed** 2020-07-19 07:18 UTC
