### ISSUE TITLE
ITK Ransac fails if the models scale is too small. 

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#361] opened 2024-11-28 17:27 UTC
**Describe the bug**
ITk-ransac implementation fails if the scales of two models are very different. Particularly when one is very slow. This affects both ALPACA and FastModelAlign (which uses logic from ALPACA) models of SlicerMorph. An example of the error is provided below:
```
ReadDataInternal ((unknown)): File D:/PHD/CT_Scan_Project/SCAPULAE/ALPACA/ORANGUTAN 3\ORA_USNM_153805_SCAP_L.ply does not contain coordinate system information. Assuming LPS.
"Model" Reader has successfully read the file "D:/PHD/CT_Scan_Project/SCAPULAE/ALPACA/ORANGUTAN 3\\ORA_USNM_153805_SCAP_L.ply" "[0.94s]"
ReadDataInternal ((unknown)): File D:/PHD/CT_Scan_Project/SCAPULAE/ALPACA/CHIMPANZEE/CHI_USNM_395820_SCAP_L.ply does not contain coordinate system information. Assuming LPS.
"Model" Reader has successfully read the file "D:/PHD/CT_Scan_Project/SCAPULAE/ALPACA/CHIMPANZEE/CHI_USNM_395820_SCAP_L.ply" "[0.66s]"
parameters are  {'projectionFactor': 1.0, 'pointDensity': 1.0, 'normalSearchRadius': 2.0, 'FPFHNeighbors': 100, 'FPFHSearchRadius': 5.0, 'distanceThreshold': 3.0, 'maxRANSAC': 1000000, 'ICPDistanceThreshold': 1.5, 'alpha': 2.0, 'beta': 2.0, 'CPDIterations': 100, 'CPDTolerance': 0.001, 'Acceleration': False, 'BCPDFolder': ''}
:: Loading point clouds and downsampling
Scale length are   0.19596030325536423 222.15980000808426
Voxel Size is  0.003562914604642986
Scaling factor is  0.0008820691378378688
------------------------------------------------------------
movingMeshPoints.shape  (2031, 3)
movingMeshPointNormals.shape  (2031, 3)
fixedMeshPoints.shape  (1976, 3)
fixedMeshPointNormals.shape  (1976, 3)
------------------------------------------------------------
FPFH generates 2 putative correspondences.
Rigid Reg, no scaling
Traceback (most recent call last):
  File "C:/Users/gsq752/AppData/Local/slicer.org/Slicer 5.7.0-2024-03-05/slicer.org/Extensions-32750/SlicerMorph/lib/Slicer-5.7/qt-scripted-modules/ALPACA.py", line 934, in onApplyLandmarkMulti
    logic.runLandmarkMultiprocess(
  File "C:/Users/gsq752/AppData/Local/slicer.org/Slicer 5.7.0-2024-03-05/slicer.org/Extensions-32750/SlicerMorph/lib/Slicer-5.7/qt-scripted-modules/ALPACA.py", line 1544, in runLandmarkMultiprocess
    array = self.pairwiseAlignment(
  File "C:/Users/gsq752/AppData/Local/slicer.org/Slicer 5.7.0-2024-03-05/slicer.org/Extensions-32750/SlicerMorph/lib/Slicer-5.7/qt-scripted-modules/ALPACA.py", line 1591, in pairwiseAlignment
    SimilarityTransform, similarityFlag = self.estimateTransform(
  File "C:/Users/gsq752/AppData/Local/slicer.org/Slicer 5.7.0-2024-03-05/slicer.org/Extensions-32750/SlicerMorph/lib/Slicer-5.7/qt-scripted-modules/ALPACA.py", line 2486, in estimateTransform
    transform_matrix, fitness, rmse = self.ransac_using_package(
  File "C:/Users/gsq752/AppData/Local/slicer.org/Slicer 5.7.0-2024-03-05/slicer.org/Extensions-32750/SlicerMorph/lib/Slicer-5.7/qt-scripted-modules/ALPACA.py", line 2020, in ransac_using_package
    ransacEstimator.SetParametersEstimator(registrationEstimator)
RuntimeError: D:\a\im\include\itkRANSAC.hxx:104:
Not enough data elements for use with this parameter estimator.
```

**To Reproduce**
Download the `Partial Photogrammetry Models` sample data bundled by SlicerMOrph extension. 
Choose Small Model as source and Large model as Target and hit Test Point Cloud subsampling. Notice that it extracts only 1 point from the small source model as oppose to expected few thousand. if you proceed with the registration, you will encounter the error above. 

This does not happen with the open3d implementation that ITK one replaced last year. 

@jcfr @dzenanz

**Comment by dzenanz** [comment] 2024-11-28 21:40
This sounds like a relatively easy issue to fix. Those distance-related parameters probably just need to be multiplied by voxel spacing somewhere. I could tackle this. Can you assign this issue to me?

**Comment by muratmaga** [comment] 2024-12-06 00:46
@dzenanz do you have time to fix this between now and Wednesday?

**Comment by dzenanz** [comment] 2024-12-06 01:08
I have not really gotten around to this. But fixing it by Wednesday sounds plausible.

**Comment by dzenanz** [comment] 2024-12-06 20:04
I am starting to look into this. The problem isn't in RANSAC, but in FPFH.
> FPFH generates 2 putative correspondences.

2 corresponding points are not enough to determine rigid transform. At least 3 are required, and ideally we want 4+ (so we can estimate uncertainty). Which means I need to look into [ITKFPFH](https://github.com/InsightSoftwareConsortium/ITKFPFH), not [ITKRANSAC](https://github.com/InsightSoftwareConsortium/ITKRANSAC).

**Comment by dzenanz** [comment] 2024-12-09 19:56
452ecbf1628e8299fd48154171ee152137e32d96 inverted the meaning of scaling checkbox in Alpaca, but not in FastModelAlign. When this option is turned on, registration works reasonably.
![image](https://github.com/user-attachments/assets/9df63566-83ac-433e-9b76-a6f06f400ff4)
PR incoming.

**Comment by muratmaga** [comment] 2024-12-09 23:15
I accidentally closed it without testing extensively. It seem to work but @smrolfe please also tes it as well.

**Closed** 2024-12-11 02:17 UTC
