### ISSUE TITLE
ExportAs broken functionality in some installations

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#71] opened 2020-07-22 21:32 UTC
ExportAs should allow users to save their volumes, markups and models from Data module using the right-click context menu. It appears this functionality works 100% of the time for Markups, if it is invoked within Markups module. However, functionality within Data module seems hit and miss, with no clear indication of why and what platforms are being affected. We have tested on 4-5 windows 10 machines, and 4 of them are not working as intended in Mac, we have 50-50 split. On linux two computers where tested and it works 100%. (Update not correct anymore. At least one Linux system seems affected).

**Comment by SlicerMorph** [comment] 2020-07-22 22:08
It appears that something weird about the module path is causing the issue. These steps seems to fix the issue but inconvenient. 
1. Install Slicer
2. Install SlicerMorph from extension catalog (accept all dependencies)
3. Restart and see that ExportAs doesn't function normally in Data module:
4. Go to Application Settings and click Restore Defaults and restart. This removes all additional module paths, but does not uninstall the extension 
5. See that GPA or any other SlicerMorph related modules are not present.
6. Click Extension manager, hit Manage Extensions. Click disable on SlicerMorph and then click enable.  This will add the SlicerMorph application back to the additional Module paths. Restart Slicer
7. See the export As works as intended. 

While this mitigates the problem, this is not a real solution, as it will take disabling/enabling all the additional extensions.

**Comment by pieper** [comment] 2020-07-22 22:46
Hmm, that is really odd behavior.  

Is there something different about the module paths before and after this procedure?  Perhaps they are in a different order and one of the dependencies causes an issue if it's loaded before the ExportAs feature?

**Comment by SlicerMorph** [comment] 2020-07-22 23:08
On a non-functional system the order of modules listed are like this:
DCM2nii
Sandbox
Auto3dm(two paths)
segmenteditor extra
RawImageGuess
SlicerMorph
SurfaceWrap
IGT (two lines)

After the procedure above, SlicerMorph is the first one and it appears to work. However, I couldn't find a way of easily reordering module paths (as in move up/down).

**Comment by pieper** [comment] 2020-07-22 23:12
Hmm, very odd.  I guess the next step if you have the patience would be to remove them one at a time and see if/when the behavior changes.

**Comment by SlicerMorph** [comment] 2020-07-22 23:42
Removing all modules (except for SlicerMorph) one by one from list and testing the application, didn't help. In fact I removed SlicerMorph from the module path, and re-add as the single item. Still didn't help. So far the only solution seems hitting the "restore defaults" and disabling/enabling from extension manager. Is it possible to do Andras's debugging solution?

**Comment by lassoan** [comment] 2020-07-23 00:11
It seems that SlicerMorph is bringing in too many extensions. You need to wait a really long time for all extensions to get installed. Restart button gets enabled when the first extension installation complete, but there are many more to wait for. If you don't wait then SlicerMorph will not be installed at all. You can check when SlicerMorph is actually installed when SlicerMorph shows up in ExtensionsHistory section in Slicer.ini. If you wait for it then the "Export as..." menu appears correctly.

**Comment by SlicerMorph** [comment] 2020-07-23 00:19
I am not sure if that's the issue. I always wait for other extensions to finish installing to restart Slicer. Plus, all other modules within SlicerMorph (GPA, semiLandmarks etc) are all available and functional.

**Comment by smrolfe** [comment] 2020-07-23 01:06
I've tested on my Windows 10 desktop and the export works as intended there. The extension manager is still not functional on the Mac, so I can't replicate the issue there. It looks like this extension manager issue is scheduled to be resolved by the end of the week: https://www.slicer.org/wiki/Documentation/Labs/ExtensionsServer#Status

**Comment by lassoan** [comment] 2020-07-23 01:13
> I am not sure if that's the issue. I always wait for other extensions to finish installing to restart Slicer. Plus, all other modules within SlicerMorph (GPA, semiLandmarks etc) are all available and functional.

Check if the c:\Users\UUUUU\AppData\Roaming\NA-MIC\Extensions-NNNNN\SlicerMorph\lib\Slicer-4.11\qt-scripted-modules\ExportAs.py file is actually there. If it is, then add log messages or breakpoints to see if it gets loaded.

**Comment by SlicerMorph** [comment] 2020-07-23 01:47
Yep, the file is there. And it also functions within Markups module. So, it is a weird combination of things...

**Comment by lassoan** [comment] 2020-07-23 17:03
It is not really weird, there are just at least two independent issues:

1. Installation of SlicerMorph: Waiting a really long time is one workaround. A proper fix would be to not let the extension manager to be closed until all extensions are installed completely.

2. Export as "not working": I don't understand this yet - I don't even know that the problem is that it does not show up or the file extensions menu does not show up or selecting an item does not do anything. If you attach a debugger and/or add log messages on a problematic computer then we will know why this problem occurs and how to fix it.

**Comment by pieper** [comment] 2020-07-23 17:09
Thanks for your help with this @lassoan 

To clarify your second point: the ExportAs module is a small thing that adds a Subject Hierarchy plugin to add a context menu action.  The odd behavior Murat is seeing is that the context menu shows up in one subject hierarchy view (markups) but not the other (data), but this only happens on some machines and seems to depend on the installation process.  This is the issue we are trying to document and fix.

The point about the "Restart" button being enabled too soon is valid, and we should track that in a Slicer issue.

**Comment by lassoan** [comment] 2020-07-23 17:15
OK, it is good to know that the issue is that the context menu does not show up. @pieper since you worked a lot on this registration mechanism with @cpinter, you know the best what could have been missed. A workaround could be to add some delay on startup but it would be much nicer to understand and fix the root cause.

**Comment by muratmaga** [comment] 2020-07-23 17:15
>     2\. Export as "not working": I don't understand this yet - I don't even know that the problem is that it does not show up or the file extensions menu does not show up or selecting an item does not do anything. If you attach a debugger and/or add log messages on a problematic computer then we will know why this problem occurs and how to fix it.

@lassoan actually it would be great if you can just install SlicerMorph extension, then open MRHead and right-click in the subject hierarachy and let us know if you see the 'Export As'

**Comment by pieper** [comment] 2020-07-23 17:21
Yes, I've been working on this and I'm really confused why the behavior would be different in these various scenarios and on different machines.  I don't think it's a python issue but rather perhaps a race condition internal to the plugin mechanism (or something).

I should clarify too, the context menu comes up in both the Markups and Data module on right click, it's just the custom action that is only visible in the Markups.

**Comment by cpinter** [comment] 2020-07-24 09:25
@muratmaga I downloaded the latest nightly yesterday, installed SlicerMorph, and I was able to see the Export As menu action.

> I should clarify too, the context menu comes up in both the Markups and Data module on right click, it's just the custom action that is only visible in the Markups.

Do you mean that it does not show up in the Data module only in Markups? It does sound like a race condition, but it's strange as there are plenty of modules that add context menu actions, in extensions and in the core as well, and this hasn't come up yet, so it must be something related to the way your module registers the plugin.

The way the actions in the tree view work is that they are [added to the menus](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx#L337-L343) on the tree view construction (setupActions call from the init function), which is a one time operation. Then, on each right-click, the plugins are [called to show](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx#L1295-L1298) the actions that apply for that particular item.
My suspiction is that when setupActions is called for the Data module's tree view, the ExportAs plugin is not registered yet, but by the time the Markups one is set up, it is.

One solution that doesn't use a timer could be to delay the setupActions call to the time the context menu is first requested. So before the `for` loops that call the `show[Visibility]ContextMenuActionsForItem` functions on the plugins, if the menus are empty, then they are set up. I don't think there would be a noticeable slowdown on this first click, and the subsequent ones would be the same as before. I could do this very quickly. What do you think?

**Comment by pieper** [comment] 2020-07-24 20:22
> My suspiction is that when setupActions is called for the Data module's tree view, the ExportAs plugin is not registered yet, but by the time the Markups one is set up, it is.

That's an interesting theory.  The [plugin is registered after startup is complete](https://github.com/SlicerMorph/SlicerMorph/blob/master/MarkupEditor/MarkupEditor.py#L43-L55) and perhaps by that time the Data tree view has already been initialized, which might depend on whether some other initialization step might have triggered it to build during application startup.

> tree view construction (setupActions call from the init function), which is a one time operation.

Couldn't this be dynamic?  E.g. with something like a vtk `MTime` that is incremented when a new plugin is registered.  That way the context menu can be regenerated it's not up to date.  It would also let extensions update their registered actions based on other events.  That would also mean adding support for unregistering plugins.

**Comment by cpinter** [comment] 2020-07-27 08:22
> something like a vtk `MTime` that is incremented when a new plugin is registered

It sounds like a good idea to me. I could also try to implement this approach to the view context menus (implemented in SH plugin logic) to simplify its usage. @lassoan what do you think?

**Comment by lassoan** [comment] 2020-07-27 13:57
Sounds good!

**Comment by muratmaga** [comment] 2020-07-29 22:50
This reproducibly fails, if the default module is set to Data instead of Welcome. To repro, see ExportAs is functioning correctly open installation from Data module. Then go to application settings and set the default module to Data, restart slicer and see if no longer works.

**Comment by pieper** [comment] 2020-07-30 00:05
Thanks for the confirmation @muratmaga 

@cpinter were you going to be able to look at this?  I hope it's an easy fix. 😄

**Comment by cpinter** [comment] 2020-07-30 08:34
This will be a rework, so probably not an easy fix. I'll try to do it soon, but need to fit it between the funded projects somehow.

**Comment by muratmaga** [comment] 2020-07-31 04:18
OK. Meanwhile we will have to revise our suggestion of having the Data module as the default startup module.

**Comment by cpinter** [comment] 2020-07-31 08:02
@muratmaga I made good progress yesterday and it seems easier than I thought, so please hang on, I'll have a fix soon.

**Comment by cpinter** [comment] 2020-07-31 12:12
Please see https://github.com/Slicer/Slicer/pull/5073

@pieper you were right, this was not a big change. I didn't touch the view context menus after all, since it is already generated on the fly.

**Comment by muratmaga** [comment] 2020-08-03 16:43
Closing, fixed by https://github.com/Slicer/Slicer/pull/5073

**Closed by muratmaga** 2020-08-03 16:43 UTC
